### PR TITLE
Add Sony and no$psx dithering

### PR DESCRIPTION
**Pull request by aybe**
This is just a proof concept, it does work.

I suggest you do A/B comparison by opening the images in different tabs as the differences are here but subtle.

In order:

- none
- Sony (libref47.pdf p.242)
- no$psx (help.htm GPU MISC):

PsyDoom_2021-07-12_09-30-06

PsyDoom_2021-07-12_09-31-31

PsyDoom_2021-07-12_09-32-08

Please note that I couldn't find the same code block for Vulkan, I suppose this is expected somehow... so this is SDL-only.

Sorry, it's on master, I switched on develop but then couldn't find `copyPsxToSdlFramebufferTexture`.

Oh and yes, as you'll see I don't do C++ on a regular basis so you'll definitely want to improve it!😁

### CODE REVIEW

**Comment by aybe** [comment]
Actually I don't like this PR very much, it should rather be an option in-game and also available for any renderer; I'll try to upgrade it when I get some free time.

**Comment by BodbDearg** [comment]
Hey @aybe thanks for investigating this. In order to implement dithering though you'd need to do it before the pixel has been converted to 16-bit, since the purpose of dithering is to trick our eyes and fake a higher precision color value using less colors. Doing it at this stage wouldn't serve much purpose, since the color has already been truncated to 16-bit. It would just be adding a constant pattern of extra unwanted noise (as in the images above) if the image is already in 16-bit format.

The Vulkan renderer can already do 32-bit rendering also (if desired), so it doesn't require dithering. I actually don't recommend people use this mode however as it makes the image look much more washed out and reduces contrast. Contrast is the key to a good looking scene and is important I believe to the grungy PSX Doom look. Here's  screenshots (32-bit and 16-bit respectively) as an example:

image
image

Since the aim of implementing dithering for the classic rendering would be to get closer to the 32-bit look, I would not be in favor of pursuing this further. I just allow a 32-bit framebuffer for Vulkan since it is dead simple to do and is something of a curiosity (for comparison) but I don't think it's worth implementing for the classic renderer - sorry. You can of course continue experimenting with this in your own fork if you like.

**Comment by aybe** [comment]
That's right, it was poorly implemented and not even right... 

And yeah, I never realized how contrast plays a key role until today!

The other thing I haven't checked about is that dithering is not applied to everything in the PSX, not sure how Doom draws things and therefore if dithering is applied in-game; one should study draw calls in no$psx to find out if it really does and when.

**Comment by BodbDearg** [comment]
PSX Doom doesn't use dithering at all, and for this reason I didn't bother to try and emulate that feature for PsyDoom's GPU. Not sure why they didn't use it, perhaps there was a performance hit associated with it...

**Comment by aybe** [comment]
This game is really interesting in terms of how it uses the PSX hardware.

I've ran it in no$psx and I'm quite baffled, it draws one pixel wide triangles! Probably to get away with the affine texturing issues...

And yes, by seeing the amount of triangles being drawn, maybe it ended up being a performance issue.

**Comment by BodbDearg** [comment]
Yep, that's precisely it. Aaron Seeler (the main programmer) worked closely with John Carmack who famously hated affine texture warp; that probably determined the direction that was taken. Fabien Sanglard has an interesting write up about the renderer here:
https://fabiensanglard.net/doom_psx/index.html

**Comment by aybe** [comment]
That's a great read! Le 22 juil. 2021 11:19, Darragh Coy ***@***.***> a écrit :
Yep, that's precisely it. Aaron Seeler (the main programmer) worked closely with John Carmack who famously hated affine texture warp; that probably determined the direction that was taken. Fabien Sanglard has an interesting write up about the renderer here:
https://fabiensanglard.net/doom_psx/index.html

**Pull request closed without merging**
