### PR TITLE
Patches for Various Maps

### PR DESCRIPTION
**Pull request by fenderc01**
I found a few more maps to patch. I will add more as I find them.

### CODE REVIEW

**Comment by BodbDearg** [comment]
Thanks for these patches @fenderc01. Let me know when you're all done and then I can review.

**Comment by fenderc01** [comment]
I will keep adding more if I find any, but you can merge this once you are ready to publish the next release.

**Comment by fenderc01** [comment]
I've gone through both Doom and Final Doom and fixed everything I came across.

I stopped fixing GEC Master Edition Beta 3 since Beta 4 is now available.

**Comment by fenderc01** [comment]
I should be done for real this time. I could go through again and nitpick every little thing, but I'm calling it good for now.

**Comment by BodbDearg** [comment]
Thanks for all of these fixes! They are now all merged into `develop` with some additional refactoring, tweaks and edits.

**Comment by fenderc01** [comment]
I noticed some things were removed. Were these intentional?

- Doom MAP38: Tricks And Traps
    - https://github.com/fenderc01/PsyDoom/blob/develop-mappatches/game/PsyDoom/MapPatcher/MapPatches_Doom.cpp#L735-L736

- Final Doom MAP26: Aztec
    - https://github.com/fenderc01/PsyDoom/blob/develop-mappatches/game/PsyDoom/MapPatcher/MapPatches_FinalDoom.cpp#L483-L484

    - https://github.com/fenderc01/PsyDoom/blob/develop-mappatches/game/PsyDoom/MapPatcher/MapPatches_FinalDoom.cpp#L492-L496

- Final Doom MAP30: Onslaught
    - https://github.com/fenderc01/PsyDoom/blob/develop-mappatches/game/PsyDoom/MapPatcher/MapPatches_FinalDoom.cpp#L657-L658

**Comment by BodbDearg** [comment]
Thanks for checking! Turns out MAP38 was a mistake - I think I got mixed up somehow on that one. I've reverted that edit.

MAP26 is intentional, however. Those walls with the opaque mid texture look strange when you shoot them since the bullets appear to just pass through them and don't leave any smoke puffs, so I intentionally reverted those.

For MAP30, I also reverted two of the changes to remove the upper unpegged flag because the texture alignment once the doors are open looks far worse after removing the flags. Even though it is strange to see the door opening without the texture moving, you spend far more time looking at it either fully opened or fully closed than in motion. Hence, the preference for it to look good in these stationary states.

**Comment by BodbDearg** [comment]
Thanks! I integrated the extra fixes above except for the optional bit mentioned. Didn't want to tweak the PSX look of the map too much so decided to leave those little ledges in...

**Pull request merged**
